### PR TITLE
Removing /gatehouse and /registerguard repos

### PR DESCRIPTION
**Pull request by jheasly**
... which have both been rolled up (registerguard -> gatehouse ->) into /GannettMedia.

### CODE REVIEW

**Comment by kleinmatic** [comment]
The accounts still seem to be operating and have repos with recent activity, while /GannettMedia 404's. I'm going to close this unless you're seeing something I'm not seeing?

**Comment by jheasly** [comment]
The only activity on `registerguard` is from the GitHub `dependabot`. I am the sole member of that repo and left that newsroom a year ago. That newsroom id down to seven now, none of them coders. None of those apps are active/used or maintained.

On GateHouseMedia, Mike Stucka did make a one-line change on https://github.com/GateHouseMedia/hurricane-tools on GateHouseMedia, so I suppose that's something.

And GannettMedia was a brain fart on my part; I meant https://github.com/GannettDigital/

And thanks for doing this!

**Comment by palewire** [comment]
If there's historic data that could be crawled and analyzed in the future, I would vote for keeping it on the list.

**Comment by jheasly** [comment]
Fine by me. Just wanted to be clear there’s no one working on registerguard and what appears to be maintenance only on one gatehousemedia app.

**Pull request closed without merging**
